### ISSUE TITLE
Add support for location permissions

### ISSUE THREAD

**Issue by LeoNatan** [wix/AppleSimulatorUtils#1]
Need to investigate where those are saved in and what process is responsible for their management. They are not in TCC.

**Comment by billburgess** [comment]
+1

**Comment by LeoNatan** [comment]
@billburgess Thanks for your support. We are in holiday right now, so I intend to come back to this toward the end of next week.

**Comment by billburgess** [comment]
I appreciate the work so far. Let me know if you need help testing. If I come across anything, I'll be sure to submit a PR.

**Comment by billburgess** [comment]
Thanks for taking a look at this so quickly. I put a hack in place to get around this, but I should be able to give it a try to see how it goes.

**Comment by LeoNatan** [comment]
Please test. Areas to test are when an app only has permission to access location in use. Currently, I  assume that both in use and always permissions can be granted. Not sure how iOS will handle if this is not the case. Please notice that the app needs to be installed before using the tool.

**Comment by billburgess** [comment]
Sounds good. My app requires Always permission to use Geofences in the background. I'll let you know if I find out anything odd or not working correctly.

**Comment by billburgess** [comment]
The command fails when I try to run it.

`applesimutils` --simulator B5267D22-FFEB-48B9-BA63-C86755D7B3AD --bundle "com.mybundle" --setPermissions `"notifications=YES, location=always"`
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory

**Comment by billburgess** [comment]
The simulator does restart in spite of the command though.

**Comment by LeoNatan** [comment]
Hmm. Could you please open a new issue so I can investigate?
