### ISSUE TITLE
Unable to change permissions for a cloned simulator device started by Xcodebuild Test. 

### ISSUE THREAD

**Issue by devstrat** [wix/AppleSimulatorUtils#102]
**Description**
Whenever I run some UI tests from Xcode it spawns a clone of a target simulator (instead of using the existing one) which is invisible both for **applesimutils** and **simctl**. These clones are usually stored here: ~/Library/Developer/XCTestDevices.  In case of simctl you can bypass this by specifying the location where these clone simulators are residing like this: 

#### xcrun simctl list | grep Booted     
>  _no output_
#### xcrun simctl --set testing list | grep Booted
> ...  
> _Phone: Clone 1 of iPhone 13 mini (AE05B8C8-8323-4429-9E14-AC6CCBB05A00) (Booted)_
> ...

However I was not able to make it work for applesimutils:
#### applesimutils --byId AE05B8C8-8323-4429-9E14-AC6CCBB05A00 -b my.bundle.id --setPermissions "userTracking=YES, notifications=YES, camera=YES, microphone=YES"
> Error: No simulator found matching “udid == "AE05B8C8-8323-4429-9E14-AC6CCBB05A00"”. See “applesimutils --help” for usage.

**Steps to Reproduce**
I guess it can be reproduced by running some UI tests from the Xcode so it'll create a "Clone 1 of Iphone X" device to run stuff against.  The device boots up, has a UDID but applesimutils just do not see it. 

**Expected Behavior**
Applesimutils successfully interacts with the booted device with specified UDID. 

**Environment**
 - macOS version: 12.5.1
 - Xcode version: 13.4
 - applesimutils 0.9.7

**Comment by billburgess** [comment]
At what point are you applying permissions? I was under the impression that the clones all get the permissions from the original device. This is similar to how running multiple sims work.

**Comment by billburgess** [comment]
Another way to be extra careful is to create your own sim for each run. This works better in CI, but you can create a named sim and boot it up, apply your permissions to the named sim, then delete when your tests are finished. This also guarantees your permissions set correctly on the device and aren’t leftover when running on the same device.

**Comment by devstrat** [comment]
> At what point are you applying permissions? I was under the impression that the clones all get the permissions from the original device. This is similar to how running multiple sims work.

What I am trying to achieve is:  
1. I invoke the test execution
2. XCTest clones an existing simulator for some target, e.g. Iphone 13, builds an app and installs it on device
3. setup method of some test class starts and invokes the applesimutils to push the permissions first
4. then the app.launch() happens and the actual test steps begin

**Comment by billburgess** [comment]
I think you should set your device permissions before step 1. Have your sim booted and permissions set before your start your test execution so that the permissions are pre-set before the tests run.
