### ISSUE TITLE
iOS 16: Set health permissions isn't working (error)

### ISSUE THREAD

**Issue by asafkorem** [wix/AppleSimulatorUtils#105]
As addressed in https://github.com/wix/Detox/issues/3597#issuecomment-1271528373

Apparently, Apple has renamed the `bundle_id` with `udId` in this `sources` table.
![image](https://user-images.githubusercontent.com/55082339/196635642-880050b4-63ea-44fa-aaa3-277d3ade249b.png)

See https://github.com/wix/AppleSimulatorUtils/blob/master/applesimutils/applesimutils/SetHealthKitPermission.m#L77

In order to fix this error, we need to replace `bundle_id` field key in the query with `udId`, only for devices with iOS >= 16 or to ignore the DB error (and query with both field names, using a try-catch mechanism).

**Comment by alarm109** [comment]
I've started looking in to this. I forked this repo and now I'm trying to find out how to test this locally? How do I make the detox package use my forked package and not the package from brew?

**Comment by GGGava** [comment]
@asafkorem fixing this seems a bit more complicated than that. `uuid` already existed in older versions and is not related to the `bundle_id`. The `bundle_id` info was moved to a new table, `logical_sources`, and now `sources` has a new column `logical_source_id`
<img width="1280" alt="Screenshot 2022-10-26 at 16 31 36" src="https://user-images.githubusercontent.com/9848506/198158149-d1a4c1bd-7b4b-475f-ac59-e434e14d7f6b.png">
<img width="1275" alt="Screenshot 2022-10-26 at 16 32 26" src="https://user-images.githubusercontent.com/9848506/198158155-9ba109ff-4506-46d1-b039-bd1df16831f4.png">

**Comment by GGGava** [comment]
I'll try to submit a fix shortly

**Comment by GGGava** [comment]
Done, tested it locally, and seems fine, I just couldn't test the delete transaction as I don't know how to replicate it.

@asafkorem if you could review/merge it asap this would help me a lot, thanks :)

**Comment by asafkorem** [comment]
Hey @alarm109, thanks for pointing on the fact that we don't have any contribution guide.
I just added one, in case you are still looking for help with testing any local changes: https://github.com/wix/AppleSimulatorUtils/blob/master/CONTRIBUTING.md.

**Comment by asafkorem** [comment]
[ASU v0.9.8](https://github.com/wix/AppleSimulatorUtils/releases/tag/0.9.8) released with the mentioned fix. Thanks @GGGava!
