### ISSUE TITLE
new release (0.9.8) has SHA256 mismatch in brew?

### ISSUE THREAD

**Issue by mikehardy** [wix/AppleSimulatorUtils#109]
**Description**

Installing the new release (literally minutes ago @asafkorem !) I see this:

```
Error: SHA256 mismatch
Expected: c628358da0ff7617b326f2d7ac77f1527f93096418ab21e6ac7f77de34bdad4f
  Actual: 7ecf43c5a6849a1c78c085c2ef59be1d2d872ab5a97b0327d882843a3c5ea9b4
    File: /Users/mike/Library/Caches/Homebrew/downloads/1976d36e0f4e447d29a0ebc0b9cc9e5849a1e9d519176d7b55f3d1a35e5bd9fa--applesimutils-0.9.8.catalina.bottle.tar.gz
```

If you are describing an issue with `brew install`:
- [x] I've run `brew doctor` and fixed all issues

I did not even know that command, but certainly, I ran it now, this on first output:

```
mike@osxvm:~ % brew doctor
Your system is ready to brew.
```

**Steps to Reproduce**
`brew update`
`brew upgrade`

**Expected Behavior**
The new release (thank you!) should install correctly

**Screenshots**

You may examine our CI run if that helps:
https://github.com/invertase/react-native-google-mobile-ads/actions/runs/3355707687/jobs/5560294929#step:16:20

**Environment**
 - macOS version: 12.6
 - Xcode version: 14.0.1

**Additional Context**

Now, this was just published. Perhaps the SHA's have not synced up, but that seems implausible? Possible, but not likely.

This happened in CI and on a local machine where I attempted to confirm. I was just unlucky and went for a release of a react-native package right as you released here so I saw it immediately ? :-)

**Comment by asafkorem** [comment]
Thanks @mikehardy, I just fixed that. 
Hope it works well for you. Sorry for the inconvenience

**Comment by mikehardy** [comment]
> Thanks @mikehardy, I just fixed that

:boom:  Confirmed working on a new `brew update && brew upgrade` run

> Hope it works well for you. Sorry for the inconvenience

Never a problem, it was just my hope the quick report was useful, I really appreciate the utility and your efforts here, cheers!

**Comment by asafkorem** [comment]
Yay, thank you! We appreciate this feedback! 🙏🏼
