### ISSUE TITLE
Build fails due to code-signing issue

### ISSUE THREAD

**Issue by holleB** [wix/AppleSimulatorUtils#11]
#### Description
Current HEAD fails to build.

#### Steps to Reproduce
Checkout HEAD (21.09.17) from github.
```
xcodebuild clean build -project applesimutils/applesimutils.xcodeproj -scheme applesimutils -configuration Release -derivedDataPath ./build
...

=== CLEAN TARGET applesimutils OF PROJECT applesimutils WITH CONFIGURATION Release ===

Check dependencies
[BCEROR]Code Signing Error: Ad Hoc code signing is not allowed with SDK 'macOS 10.13'

Clean.Remove clean 
...

** CLEAN SUCCEEDED **

=== BUILD TARGET applesimutils OF PROJECT applesimutils WITH CONFIGURATION Release ===

Check dependencies
Code Signing Error: Ad Hoc code signing is not allowed with SDK 'macOS 10.13'

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

#### Device, macOS and Xcode Versions
macOS 10.12.6, XCode 9.0 (9A235)

**Comment by LeoNatan** [comment]
Are you using `brew` or building directly?
Try using `export CODE_SIGNING_REQUIRED=NO && ` before your build command (either `brew` or `xcodebuild`).

**Comment by holleB** [comment]
I tried both, same error. Still failing.

**Comment by LeoNatan** [comment]
Are you building using brew or manually?

**Comment by holleB** [comment]
both, brew and xcodebuild. `export CODE_SIGNING_REQUIRED=NO` didn't work also. But it's a heisenbug. I can't reproduce it on my macbook, only on my dev machine besides seemingly identical xcode setup... *shrug*

**Comment by holleB** [comment]
Ok, so for my setup the fix is setting `CODE_SIGN_IDENTITY` from `"-"` to `""`. Do you want a pull request for that?

**Comment by dtuite** [comment]
I just hit this and either retapping or specifying `--HEAD` seemed to fix it. No idea why.

```
brew install applesimutils
==> Installing applesimutils from wix/brew
==> Downloading https://github.com/wix/AppleSimulatorUtils/archive/0.5.7.tar.gz
==> Downloading from https://codeload.github.com/wix/AppleSimulatorUtils/tar.gz/0.5.7
####################### 100.0%
Error: SHA256 mismatch
```

```
brew tap wix/brew
brew install --HEAD applesimutils
```

**Comment by LeoNatan** [comment]
@dtuite Can you please try with the latest versions?

**Comment by dtuite** [comment]
@LeoNatan will try again next time I get a chance. That might not be anytime soon though. I'll let you know.

**Comment by LeoNatan** [comment]
I’m closing for now. Feel free to reopen if needed.
