### ISSUE TITLE
Xcode 15 > Unable to run commands

### ISSUE THREAD

**Issue by bryanlatten** [wix/AppleSimulatorUtils#116]
**Description**

After upgrading to xcode 15, applesimutils can't seem to run commands against any simulator. I'm using applesimutils in service of detox framework.
Prior to xcode upgrade, everything worked great.
 
```
ChildProcessError: Command failed: applesimutils --byId 452474B3-B45E-46BB-B2D5-99D919815B0B --clearKeychain
    *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[5]. See "applesimutils --help" for usage.
     `applesimutils --byId 452474B3-B45E-46BB-B2D5-99D919815B0B --clearKeychain` (exited with error code 255)
```

If you are describing an issue with `brew install`:
- [x] I've run `brew doctor` and fixed all issues

**Steps to Reproduce**
```
$ xcrun simctl list | grep 1C22E317-AC77-483C-9689-5A5AC4C1E51A
iPhone 14 (1C22E317-AC77-483C-9689-5A5AC4C1E51A) (Booted)


$ applesimutils --byId 1C22E317-AC77-483C-9689-5A5AC4C1E51A --clearKeychain
*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[5]. See “applesimutils --help” for usage.
```

**Expected Behavior**
Commands should return successfully after taking action

**Screenshots**

**Environment**
 - applesimutils: 0.9.9 (latest)
 - macOS version: 13.5.2
 - Xcode version: 15.0
    - Xcode has this nasty surprise of auto-updating. I would never do it myself. 

**Additional Context**
Thanks for the help!

**Comment by B0Y3R** [comment]
+1 Having the same issue

**Comment by CameronWhiteside** [comment]
Same here as well

**Comment by asafkorem** [comment]
Thanks for the report @bryanlatten, I'll look into it in a few days.

**Comment by MKmiecik1** [comment]
The same issue is here, so looks like global, thanks @asafkorem for info, waiting for results.

**Comment by cunderw** [comment]
+1 here

**Comment by ShahilMangroliya** [comment]
> +1 here, this is fixed by #115

how to install that specific PR

**Comment by B0Y3R** [comment]
If anyone needs a workaround while waiting for this fix, re-installing xcode 14, dragging it into the applications and choosing replace allowed me to get around this for now. 

you can find the xcode 14 install here: https://developer.apple.com/download/all/?q=xcode

**Comment by cunderw** [comment]
> > +1 here, this is fixed by #115
> 
> 
> 
> how to install that specific PR
> 
> 

Clone forked repo and follow the instructions to build the binary. Then replace the binary on your system with the output.

**Comment by cunderw** [comment]
> If anyone needs a workaround while waiting for this fix, re-installing xcode 14, dragging it into the applications and choosing replace allowed me to get around this for now. 
> 
> 
> 
> you can find the xcode 14 install here: https://developer.apple.com/download/all/?q=xcode

You can also build the binary yourself from pr #115

**Comment by asafkorem** [comment]
https://github.com/wix/AppleSimulatorUtils/pull/115 was merged. I will release a new version of ASU soon

**Comment by asafkorem** [comment]
AppleSimulatorUtils v0.9.10 was released with this fix. Thanks to @ksuther for his great contribution

In order to upgrade ASU using brew:
```
brew tap wix/brew
brew update
brew install wix/applesimutils
```

**Comment by bryanlatten** [comment]
@asafkorem looks very much solved, thank you!

**Comment by B0Y3R** [comment]
@asafkorem @ksuther Thank you!!
