### ISSUE TITLE
homebrew: upgrade to 0.9.10 fails due to SHA mismatch

### ISSUE THREAD

**Issue by achou11** [wix/AppleSimulatorUtils#118]
**Description**

Identical to https://github.com/wix/AppleSimulatorUtils/issues/109. Attempting to update to 0.9.10 via homebrew results in an error about a SHA mismatch.

```sh
Error: SHA256 mismatch
Expected: abf970464a590ebbcae70f79d6755201167da1d5c90fc8f8124957a7b14c295e
  Actual: e3971b3f6d5b7ef010d811b1c1b44492e496eebecf7ef934d6bcfca750828152
    File: /Users/andrewchou/Library/Caches/Homebrew/downloads/c930720be2f36036b223e6ef02648943ace9001ad4744a6a4837295ccf4caf3f--applesimutils-0.9.10.catalina.bottle.tar.gz
```

attempting to upgrade from 0.9.9 to 0.9.10

If you are describing an issue with `brew install`:
- [X] I've run `brew doctor` and fixed all issues

**Steps to Reproduce**

1. `brew update`
2. `brew upgrade`

**Expected Behavior**

Installation works

**Screenshots**

N/A

**Environment**
 - macOS version: 13.6 (Ventura)
 - Xcode version: 15.0

**Additional Context**

**Comment by asafkorem** [comment]
can you please try `brew update`?

**Comment by achou11** [comment]
seems like it works, thanks for the fix!
