### ISSUE TITLE
A way to clear the keychain? 

### ISSUE THREAD

**Issue by ahmedlhanafy** [wix/AppleSimulatorUtils#14]
#### Description
Is there any way to clear the keychain? I used to do this
```js
await device.deviceDriver._fbsimctl._execFbsimctlCommand({
    args: `${device._deviceId} clear_keychain`,
});
```
 in older versions of Detox and since Detox is now using this library I wanted to know if there is a way to clear the keychain?

**Comment by LeoNatan** [comment]
This is not currently possible. We’ll look into it.

**Comment by LeoNatan** [comment]
This is now supported by `applesimutils`.

**Comment by ahmedlhanafy** [comment]
@LeoNatan Thanks for the quick fix! Now, how can I clear the cache from Detox?

**Comment by LeoNatan** [comment]
You need to call applesimutils directly.

**Comment by kumarpatel** [comment]
@ahmedlhanafy Did you ever figure out how to call applesimutils directly?
Here's what I've tried so far:
```await device.deviceDriver._applesimutils._execFbsimctlCommand({args: `${device._deviceId} clear_keychain`});```
```await device.deviceDriver._applesimutils({args: `${device._deviceId} clear_keychain`});```
```await device._applesimutils._execFbsimctlCommand({args: `${device._deviceId} clear_keychain`});```
`console.log(device.deviceDriver._applesimutils)`
outputs ```AppleSimUtils {}```

Any help on this will be appreciated. Thanks

**Comment by kumarpatel** [comment]
nvm. got it working.

```
await device.deviceDriver._applesimutils._execAppleSimUtils({
      args: `--simulator "${device._deviceId}" --clearKeychain`,
    });
```
