### ISSUE TITLE
Feature Request: Mail Account

### ISSUE THREAD

**Issue by billburgess** [wix/AppleSimulatorUtils#21]
#### Description
It would be massively handy to spoof or mock a mail account in the simulator to avoid getting the system alert for No Mail Accounts. Testing logic around sending email from the app is near impossible.

#### Steps to Reproduce
1. Mock or stub the MFMailComposeViewController -canSendMail to YES.
2. Alloc/Init the MFMailComposeViewController.
3. Observe the system alert that can't be closed that persists for the remainder of your test suite.

#### Device, macOS and Xcode Versions
All iOS Simulators and Xcode versions that I've worked with going back to at least Xcode 7.

**Comment by billburgess** [comment]
Unless someone has a better way to override the alloc/init of the MFMailComposeViewController to prevent the alert. It may not even be possible, but thought I'd ask.

**Comment by LeoNatan** [comment]
Hi Bill, thanks for your suggestion.

While I agree that this is a problem, it's not something suitable for applesimutils. This focuses on simulator utilities and not compile-time helpers.

**Comment by LeoNatan** [comment]
I wonder, if you add an iCloud account in your simulator, does `+[MFMailComposeViewController canSendMail]` return `YES`?
