### ISSUE TITLE
applesimutils --list hangs but sudo applesimutils --list works?

### ISSUE THREAD

**Issue by joerichsen** [wix/AppleSimulatorUtils#23]
#### Description
When I try to run

```applesimutils --list```

it just hangs.

This is with the newest version 0.5.19.

But when I run the command with sudo

```sudo applesimutils --list```

it works. So it seems to be some kind of permission issue?

#### Steps to Reproduce
* install applesimutils
* run ```applesimutils --list```
* it hangs

#### Device, macOS and Xcode Versions
MacOS High Sierra Version 10.13.2 (17C205)
Xcode Version 9.2 (9C40b)

**Comment by LeoNatan** [comment]
What happens if you run `xcrun smctl list`?

**Comment by joerichsen** [comment]
Thanks for looking into this :-)

```xcrun simctl list | head -5```

gives me

```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
```

so that seems to work fine.

More debug info: When I look into console log and try to run

```
applesimutils --list
```

it gives me the following warnings

![image](https://user-images.githubusercontent.com/1052/34812561-773924a4-f6a6-11e7-8334-dabe2f379f2a.png)

I don't know if it runs in some sort of sandboxed homebrew environment, when I run the command without sudo?

**Comment by LeoNatan** [comment]
I don't think that's related. I also see other people getting it for unrelated reasons.

Have you made any changes to your `/usr/bin/` permissions?
When you call `--list`, all the tool does is call `usr/bin/xcrun` with `@"simctl", @"list”, @"--json”` params. I don't see any reason for it to fail, while you running the command manually succeeding.

**Comment by LeoNatan** [comment]
If you run
```
ls -la /usr/bin/xcrun
-rwxr-xr-x  1 root  wheel  17952 Oct 14 08:28 /usr/bin/xcrun
```

What permissions do you get on that file?

**Comment by joerichsen** [comment]
I get this
```
ls -la /usr/bin/xcrun
-rwxr-xr-x  1 root  wheel  17952 Dec  1 20:39 /usr/bin/xcrun
```

**Comment by LeoNatan** [comment]
So it seems the same. This is a strange issue.

**Comment by joerichsen** [comment]
I just debugged  in Xcode

![image](https://user-images.githubusercontent.com/1052/34826104-8bc1cd34-f6d5-11e7-94e4-0051a1f6cf8a.png)

On my machine it hangs in line 70, but if I comment the line out, everything seems to work :-)

I have no idea on why it hangs in that line, but maybe it's just on my Mac, so I'll go ahead and close this issue.

**Comment by LeoNatan** [comment]
That’s not a solution. 😄
It just means you are not waiting for the process to finish.

**Comment by joerichsen** [comment]
OK, inspired by https://stackoverflow.com/a/39281558 I tried moving line 70

```swift
[listTask launch];
	
NSFileHandle* readFileHandle = [outPipe fileHandleForReading];
NSData* jsonData = [readFileHandle readDataToEndOfFile];

[listTask waitUntilExit];
```

after the readFileHandle stuff and that seems to fix the problem on my machine.

**Comment by joerichsen** [comment]
I don't know if that's an OK solution - I'm not a Mac programmer 😄

**Comment by LeoNatan** [comment]
Hmm interesting, let me test this.

**Comment by joerichsen** [comment]
Awesome 👍 

Just tried out the the new 0.5.21 version and it works like a charm.

**Comment by LeoNatan** [comment]
Good!
