### ISSUE TITLE
Support xcenv

### ISSUE THREAD

**Issue by nikolaykasyanov** [wix/AppleSimulatorUtils#24]
#### Description

[xcenv](http://xcenv.org) is a tool that lets you define Xcode version on a project/directory/shell basis.
It's especially useful on CI because it's possible to have different branches using different Xcode versions to build.

As far as I can see, AppleSimulatorUtils uses full path to `xcrun` binary, thus missing xcenv shims. I'm not sure what the best way is to address it, although using just `xcrun` instead of the full path should work for both cases.

I'd be happy to implement it myself if you're okay with that and could give me some pointers.

**EDIT**: wording.

**Comment by LeoNatan** [comment]
Hello, thanks for your suggestion!

I would like to first understand what xcenv solves and how, so I can better understand what is needed.
If calling the path-most `xcrun`, perhaps a call to `which xcrun` first will solve this?

**Comment by nikolaykasyanov** [comment]
In a nutshell, xcenv creates a set of shims for Xcode binaries (`xcrun` included) in `~/.xenv/shims` and prepends this directory to PATH. When a command (`xcrun` for example) is performed in the shell, the respective shim is invoked, determines Xcode version and invokes the actual binary with a proper `DEVELOPER_DIR` environment variable value.

**Comment by LeoNatan** [comment]
How does the shell know which shim to call?

**Comment by nikolaykasyanov** [comment]
If one runs `xcrun` and `~/.xenv/shims` is first on the PATH then `~/.xcenv/shims/xcrun` will be executed.

**Comment by LeoNatan** [comment]
Great. So it does seem asking the system `which` will work.

**Comment by LeoNatan** [comment]
I just added implementation and will release 0.5.22. Please try and see if it is properly supported.

**Comment by nikolaykasyanov** [comment]
@LeoNatan thank you! Works great.
