### ISSUE TITLE
iOS Healthkit Permissions not being set

### ISSUE THREAD

**Issue by lewisbrotchie** [wix/AppleSimulatorUtils#26]
#### Description
We're using healthkit in our app and attempting to run e2e tests in Detox. When providing health as an argument for ```launchApp()``` it does not set the permission for allowing access to "Steps" and "Mindful Minutes", so the permission sheet still shows which times out any other tests.

#### Steps to Reproduce
The way i've been setting the permissions is as follows (to ensure it's set on initial launch)
```
beforeAll(async () => {
    await detox.init(config, { launchApp: false });
    await device.launchApp({
        permissions: {
            notifications: "YES",
            health: "YES"
        }
    });
});
```

It's definitely running this code as the notification permissions are being set correctly, and the app does appear on Settings > Privacy > Health on the simulator. It shows "Steps" and "Mindful Minutes" as being un-toggled though. 

#### Device, macOS and Xcode Versions

- **applesimutils** 0.5.22
- **detox** 7.3.3
- **macOS** 10.13.4
- **Xcode** 9.4
- **iPhone 7** 11.4
- **node** 9.11.1

**Comment by etaiklein** [comment]
👍

**Comment by LeoNatan** [comment]
Could you please provide the code necessary for requesting Steps and Mindful?

**Comment by LeoNatan** [comment]
Ping

**Comment by lewisbrotchie** [comment]
`[self.healthStore requestAuthorizationToShareTypes:writePermissions readTypes:readPermissions completion:^(BOOL success, NSError *error) {
                    if (!success) {
                        NSLog(@"Error with HealthKit authorization: %@", error);
                        resolve(@(NO));
                        return;
                    } else {
                        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                            resolve(@(YES));
                        });
                    }
                }];`

where readPermissions are "Steps" and "Mindfulness" being passed through

**Comment by LeoNatan** [comment]
Sorry, I haven't had time to look yet, but haven't forgotten.

**Comment by pdaw** [comment]
@LeoNatan any news?

**Comment by LeoNatan** [comment]
Sorry, I have not yet looked. Will try to do it soon.

**Comment by LeoNatan** [comment]
So, investigated this for a while. There is healthdb.sqlite which tracks of which apps are registered with HK and also, in a different table, which data type have been granted read and/or write permission, per type. For the last part, I didn't find a way to obtain all data types programmatically somehow. I guess I could spam with some range, like 1-200 types and give or take permission to all, for both read and write.

**Comment by LeoNatan** [comment]
Added support for HealthKit in iOS 12.0 simulators and above. Will release a version soon.
