### ISSUE TITLE
Support user login permission 

### ISSUE THREAD

**Issue by David-Dwornick** [wix/AppleSimulatorUtils#27]
#### Description
![login_alert 2](https://user-images.githubusercontent.com/6088234/40993957-eda03ddc-68c8-11e8-9d6e-6a23ae04200d.png)

We have an application that uses SFAuthenticationSession, which users are prompted by dialog to accept.  Is it possible to add support so we are able to accept this alert?

**Comment by LeoNatan** [comment]
Could you please create a demo project which triggers this prompt? I might be able to take a look.

**Comment by LeoNatan** [comment]
Reading the documentation, I don't think this is possible. The consent dialog appears every time you use the API, so it's not possible to fake that other than mocking this API for your tests.
