### ISSUE TITLE
Setting permission not working

### ISSUE THREAD

**Issue by billburgess** [wix/AppleSimulatorUtils#3]
When run locally on a clean simulator (app not installed) the command does not set the permissions for notifications.

1. Open the iOS Simulator (using iPhone 7)
2. Open terminal
3. Run command `applesimutils --simulator "iPhone 7" --bundle "my.bundle.id" --setPermissions "notifications=YES"`
4. Simulator restarts.
5. Run test suite
6. Apple Notification Permission dialog still appears while tests are running

Am I missing something?

**Comment by LeoNatan** [comment]
Did you run this before or after installing the app on the simulator? Maybe this is causing the issue, but it shouldn't from my testing.

**Comment by LeoNatan** [comment]
You need to provide the simulator UUID for the `--simulator` argument. Use `simctl list` and copy the UUID of the simulator.

**Comment by LeoNatan** [comment]
I've opened an enhancement issue for this. I'll see what I can do.

**Comment by billburgess** [comment]
I tried once with the simulator UUID. Maybe that is the trick. Subsequent runs still seemed to run against the open iPhone 7 simulator and restarted the Springboard. So something is working on the simulator.

The main for me is how would I be able to use this in my CI script. I won't know the UUID on the remote machine where my tests are running, so I can't hardcode a UUID in. Is it possible to fuzzy logic the match and run on the closest match? Or first match?

**Comment by LeoNatan** [comment]
For now, you can use `fbsimctl "iPhone 7" list | tr -s ' ' | cut -d ' ' -f 1 | head -1` to obtain the UUID of the simulator you want to use in your CI.

**Comment by LeoNatan** [comment]
It might be possible to somehow filter `xcrun simctl list` as well, but the output there is more complex / less convenient.

**Comment by billburgess** [comment]
I'll give that a try. I appreciate the help.

**Comment by billburgess** [comment]
Here is the command I ultimately ended up using in my yml file to set the permission. It does work once I set the permissions on the UDID rather than the name.

`applesimutils --simulator $(fbsimctl 'iPhone 7' list | tr -s '' | cut -d ' ' -f 1 | head -1) --bundle "com.myapp.bundle" --setPermissions "notifications=YES"`

**Comment by LeoNatan** [comment]
Thanks for posting this. I will work on a future improvement to allow specifying the simulator by name.
