### ISSUE TITLE
Support TouchID functionality 

### ISSUE THREAD

**Issue by fedeerbes** [wix/AppleSimulatorUtils#32]
#### Description

I want to know if there is a way to test TouchID, currently i'm using Detox as e2e framwork, and i have touchID logic in my app. It would be nice simulate success and failure and interactions with system alerts binding to the process.

**Comment by LeoNatan** [comment]
I have found a way to implement Touch ID/Face ID enrollment as well as matching and non-matching. Will implement this today.

**Comment by fedeerbes** [comment]
Great news @LeoNatan, thanks!
