### ISSUE TITLE
applesimutils adds same records into TCC.db

### ISSUE THREAD

**Issue by K-Be** [wix/AppleSimulatorUtils#34]
#### Description
applesimutils insets same records into TCC.db on iOS simulator 12.x.

#### Steps to Reproduce
1. Install XCode 10 with iOS 12.0 sdk.
2. Install applesimutils 0.5.22
3. Launch: 
`     applesimutils --byOS "12.0" --byName "iPhone SE" --bundle "com.wix.Tst" --setPermissions "photos=YES, notifications=YES, reminders=YES,location=inuse"`
4. Open TCC.db in some SQLite viewer.
5. Execute request: 
  ` select * from access where service == "kTCCServicePhotos" AND client == "com.wix.Tst"`
6. You will get next Result: 

> "kTCCServicePhotos"	"com.wix.Tst"	"0"	"1"	"1"							"1538470605"
> "kTCCServicePhotos"	"com.wix.Tst"	"0"	"1"	"1"							"1538470614"
> "kTCCServicePhotos"	"com.wix.Tst"	"0"	"1"	"1"							"1538470624"

It is not correct behaviour because should be one record for "kTCCServicePhotos". 

If a user prohibited access to photos, a record with `allowed = 0` also will present, and OS will not allow access to photos to the application. 

#### Device, macOS and Xcode Versions

Xcode 10.0
Mac OS 10.13.6 (17G65)

**Comment by LeoNatan** [comment]
Thanks
Is this issue only on iOS 12, or is it more strict?
I wonder if this is an issue with all tcc.db access so far.

**Comment by K-Be** [comment]
I did not face with this feature before iOS 12.0.
