### ISSUE TITLE
How to disable push notifications

### ISSUE THREAD

**Issue by LayMuiToh** [wix/AppleSimulatorUtils#36]
applesimutils version 0.5.22

My app is in react native and running a test using the iOS simulator to automate the login screen
however whenever I launch my app in the iOS simulator, there is a push notifications popup 

1. Build the app via the command
react-native run-ios --configuration Debug --simulator="iPad (5th generation)"
2. Start the appium server 
npm run start:appium
3. Start the e2e test
npm run test:e2e:ios

In my test code, I use this command but it still didn't disappear
 describe('Login Test', () => {
 // beforeAll(async () => await driver.init(config));
  afterAll(async () => await driver.quit());
  beforeAll(async () => {
    await driver.init(config, {launchApp: false});
    await driver.launchApp({
     permissions: {notifications: 'YES'}
    });
    });

react-native-cli: 2.0.1
react-native: 0.55.4

macOS: 10.3.16
Xcode: 10 , Legacy Build System in Project Setting
iPad (5th generation) 
PlatformVersion: 10.3

**Comment by LeoNatan** [comment]
AppleSimUtils is agnostic to your developer environment. You should call it with the set permissions command after you install your app on the simulator and before running your tests.

**Comment by LayMuiToh** [comment]
@leoNatan, thanks I got this works by adding  "autoAcceptAlerts": "true" to the desired Capabilities in my package.json
