### ISSUE TITLE
appium web driver clear() didn't work on the iOS simulator

### ISSUE THREAD

**Issue by LayMuiToh** [wix/AppleSimulatorUtils#37]
// wd example let element = await driver.elementByAccessibilityId("SomeAccessibilityID"); 
await element.clear();

the clear() does not work. the textfield didn't get cleared.

appium: 1.9.1
wd: 1.11.0
xcode: 10

**Comment by LeoNatan** [comment]
I am sorry, what does this have to do with AppleSimUtils?

**Comment by LeoNatan** [comment]
I still fail to see what it has to do with this project.
