### ISSUE TITLE
iCloud Keychain Alert Dialogs / Keychain Permissions

### ISSUE THREAD

**Issue by fbartho** [wix/AppleSimulatorUtils#38]
#### Description

If you make an app that has keychain password integration, some alert dialogs appear that ask you if you want to save the password in your keychain. -- Is there a permissions flag that will bypass this dialog?

We would try to get detox to dismiss the dialog, but it can't find it in the hierarchy. :(

![image 2](https://user-images.githubusercontent.com/209712/48792645-9d732f80-eca9-11e8-8c3d-59e737124177.png)

#### Device, macOS and Xcode Versions

- iOS 11, 12 
- Xcode 9.4.1 / Xcode 10

**Comment by LeoNatan** [comment]
This is not a persistent setting I can modify on disk. So unfortunately, there is little I can do to help here. I suggest mocking your API so that it is not shown by the system.
