### ISSUE TITLE
Open simulator with microphone enable

### ISSUE THREAD

**Issue by BoazWarshawsky** [wix/AppleSimulatorUtils#40]
Sorry for the very limited details, and sorry for using this place for asking question of how to use the tool.
My question is how I can launch simulator with microphone enable? and by that avoid the message of: “Xcode.app” would like to access the microphone.

Thanks

**Comment by LeoNatan** [comment]
I don't think this is related to AppleSimUtils. This is the Mac's own privacy control firing up as for some reason the Simulator needs permission to the microphone. While the two systems are quite the same (tcc), modern macOS security will prevent any tampering of the TCC database on the Mac itself unless you have SIP disabled (you shouldn't). Either way, this sounds more like an Apple bug than anything else, so please open a bug report with them.
