### ISSUE TITLE
Installing old version against xcode 9

### ISSUE THREAD

**Issue by Nick-Lucas** [wix/AppleSimulatorUtils#41]
#### Description

We are trying to install applesimutils on a new developer's machine and receive this error:

```
==> Installing applesimutils from wix/brew
Error: Your Xcode (9.4.1) is too outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
```

Because of React Native limitations we can't yet upgrade to XCode 10, and are stuck on XCode 9, so we need to install an older version of applesimutils.

We can't figure out how to install `0.5.23` as homebrew doesn't provide a canonical way to achieve this, and messing around with the https://github.com/wix/homebrew-brew repository with the usual wisdom isn't working:

* We've tried adapting this: https://danepowell.com/blog/homebrew-formula-versions
* We've tried downloading the tar locally and using the build script from the formula, which also fails.

Is there a right way to install an older version of this tool?

#### Device, macOS and Xcode Versions

XCode 9.4.1

macOS 10.14.1

homebrew 1.8.6

**Comment by LeoNatan** [comment]
This is unrelated to applesimutils.

You are running macOS 10.14, so brew requires you to install Xcode 10. This is a design choice they've made and we can't change that. Open an issue with brew.
Brew also doesn't properly support versions, so there is little I can do to help.

You can do a workaround where you have Xcode 10 and Xcode 9 installed side by side. Set 10 as the default and install applesimutils normally. Then switch back to Xcode 9 for your own work.

**Comment by Nick-Lucas** [comment]
Thanks Leo, we'll look into this!

**Comment by lizatniche** [comment]
@Nick-Lucas any traction on this? running into the same issue.

**Comment by Nick-Lucas** [comment]
@lizatniche unfortunately not. Christmas holidays came around so we haven't looked at it.

The suggestions above do look useful, but after my colleague sunk half a day failing to make it work I've suggested we instead focus on getting our project updated for xcode 10, as the path to this looks to be well travelled by others.

<rant>I realise this problem is caused by decisions made up the chain, but it's utterly infuriating that tools we are tied to by the ecosystem are willing to jettison support for old versions within weeks of new releases. It just makes projects like AppleSimUtils look bad through no fault of their own</rant>

**Comment by LeoNatan** [comment]
Just wanted to mention that there is now a workaround in applesimutils where you can install even with older Xcode.
