### ISSUE TITLE
applesimutils --list --byType iPhone XR" --byOS "12.1" hangs

### ISSUE THREAD

**Issue by rodrigorm** [wix/AppleSimulatorUtils#45]
#### Description

When I try to run

```sh
applesimutils --list --byType iPhone XR" --byOS "12.1"
```

it just hangs.

But when I run

```sh
applesimutils --list --byOS "12.1"
```

`applesimutils --list` works too.

I am using the version `0.6.4`.

#### Steps to Reproduce

- Install applesimutils
- Run `applesimutils --list --byType iPhone XR"`
- It hangs

#### Device, macOS and Xcode Versions

macOS High Sierra 10.13.6 (17G5019)
Xcode 10.1 (10B61)

**Comment by rodrigorm** [comment]
I have found that the "iPhone XR" is the problem, when I run using "iPhone 7" or other name its works.

**Comment by LeoNatan** [comment]
Most likely, you are misspelling XR. Make sure to list all devices and see the correct spell.

**Comment by rodrigorm** [comment]
You are right, reading the output carefully I have found the problem, I have copied the name from `.name` property instead of `.deviceType.name` wich is `"iPhone XR"` and `"iPhone Xʀ"` respectively according to the following output excerpt:

```
  {
    "availabilityError" : "",
    "os" : {  
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Developer\/Library\/CoreSimulator\/Profiles\/Runtimes\/iOS.simruntime",
      "availabilityError" : "",
      "buildversion" : "16B91",
      "availability" : "(available)",
      "isAvailable" : true,
      "identifier" : "com.apple.CoreSimulator.SimRuntime.iOS-12-1",
      "version" : "12.1",
      "name" : "iOS 12.1"
    },
    "availability" : "(available)",
    "deviceType" : {
      "name" : "iPhone Xʀ",
      "bundlePath" : "\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform\/Developer\/Library\/CoreSimulator\/Profiles\/DeviceTypes\/iPhone Xʀ.simdevicetype",
      "identifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-XR"
    },
    "udid" : "ACC10065-E7D3-44FB-9ED7-0C4FB6FAFBC8",
    "isAvailable" : true,
    "state" : "Shutdown",
    "name" : "iPhone XR"
  },
```

Thanks for your quick answer, and sorry for taking your time.

**Comment by LeoNatan** [comment]
Hehe, no worries. 

It used to be "XR", I think, but then they restyled it later.
