### ISSUE TITLE
Unable to install applesimutils on a system with Xcode 9.4

### ISSUE THREAD

**Issue by llostris** [wix/AppleSimulatorUtils#49]
**Description**
Unable to install applesimutils on a system running Xcode 9.4.
It results in an error:
```
==> Installing applesimutils from wix/brew
applesimutils: A full installation of Xcode.app 10.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.
```

The error started occurring today, it is probably related to the release of version 0.6.5

If you are describing an issue with `brew install`:
- [ ] I've run `brew doctor` and fixed all issues

**Steps to Reproduce**
On bitrise, run image `Xcode 9.4.x on macOS 10.13 (High SIerra)` and try installing applesimutils.
Try to install applesimutils on mac with Xcode 9.4 only.

**Expected Behavior**
We'd like to be able to install applesimutils (our bitrise test suite is broken currently because of this issue) on a system with Xcode 9.4. If the latest package has a change that is not backwards-compatibile, I think it would be good if there was an option to install the previous version of the package.
However, I don't think it's possible to access 0.6.4 in any way at this point?

**Environment**
 - macOS version: 10.13
 - Xcode version: 9.4

**Comment by LeoNatan** [comment]
Hmm right, I made a change to require Mojave. I might not be as informed to all the users. I’ll make it available for Xcode 9/HS. Or is there need for further back?

**Comment by LeoNatan** [comment]
0.6.6 is out with support for Xcode 8 & 9, macOS Sierra & High Sierra

**Comment by llostris** [comment]
Yes, that fixed the issue, thanks for a quick fix!
