### ISSUE TITLE
New location permission generates error

### ISSUE THREAD

**Issue by billburgess** [wix/AppleSimulatorUtils#5]
The command generates an error when using the location=always permission. If the simulator is open, it does restartSB.

`applesimutils --simulator B5267D22-FFEB-48B9-BA63-C86755D7B3AD --bundle "com.mybundle" --setPermissions "notifications=YES, location=always"`
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory

**Comment by LeoNatan** [comment]
What Xcode and what simulator version are you trying?
Where is your Xcode installed (i.e. `xcode-select -p`)?

**Comment by billburgess** [comment]
After running my test suite using that command, all of my tests passed and the location dialog does not get presented.

1. Reset Simulator
2. Start simulator to be used
3. Execute command to set permissions (error does show)
4. Run test suite

Using Xcode Version 8.3.1 (8E1000a). 10.3 iPhone 7 simulator. /Applications/Xcode.app/Contents/Developer

**Comment by billburgess** [comment]
No, the app is not installed prior to running the command, but does seem to work. I'll try it again running build-for-testing to see how it goes.

**Comment by billburgess** [comment]
`build-for-testing` doesn't install the app to the simulator. I ran that first, then tried to run the command and get the same error.

**Comment by LeoNatan** [comment]
Right, the `build-for-testing` action only creates an .app that can be installed using `xcrun simctl install`. I will try to find a solution for this problem tomorrow.

**Comment by LeoNatan** [comment]
OK, so it turns out what I said is incorrect. You do not have to have the application installed. I fixed the issue.

**Comment by billburgess** [comment]
Sounds good. I'll give it another test run on my CI build.
