### ISSUE TITLE
Unable to install. "Expecting keyword_end" erros

### ISSUE THREAD

**Issue by RockinRonE** [wix/AppleSimulatorUtils#50]
**Description**
Ran the install commands `brew tap wix/brew`, which worked, and then `brew install applesimutils` which failed. 

If you are describing an issue with `brew install`:
- [x] I've run `brew doctor` and fixed all issues

**Screenshots**
`Error: applesimutils: /usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:4: syntax error, unexpected <<, expecting keyword_end
<<<<<<< HEAD
  ^
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:17: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:23: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Detox Instruments 1.10.10255
  ^
/usr/local/Homebrew/Library/Taps/wix/homebrew-brew/applesimutils.rb:23: unexpected fraction part after numeric literal
>>>>>>> Detox Instruments 1.10.10255`

**Environment**
 - macOS version: 10.14.4
 - Xcode version: 10.2.1

**Additional Context**
Logs: 
https://gist.github.com/RockinRonE/a8eccf647874d7508706e1dd0d773767

**Comment by LeoNatan** [comment]
Please read the readme.

**Comment by LeoNatan** [comment]
> I've run brew doctor and fixed all issues

Also, I doubt you've done this because doctor complains about the conflicts there.

**Comment by RockinRonE** [comment]
I didn't realize it was a blocker to installing. Brew says to not mind the warnings, I'll address them.

**Comment by LeoNatan** [comment]
I tap and tap should solve it.

**Comment by RockinRonE** [comment]
For some reason it was a merge confilct in appsimutils.rb. I resolved this and now it works.
