### ISSUE TITLE
Can not find simulators

### ISSUE THREAD

**Issue by Desintegrator** [wix/AppleSimulatorUtils#53]
**Description**
applesimutils can not find any simulators.

`xcrun simctl list devices` shows:

-- iOS 10.2 --
iPhone 5s 10.2 (A86D0F25-0A31-4E26-B843-662BB715A758) (Shutdown)
iPhone 6 (B0F904AB-F0E0-4680-B611-7CD405592AD5) (Shutdown)
iPhone 6 Plus (7967BA29-3033-4376-96F5-2AFCD7892633) (Shutdown)
iPhone 6s (0A64B869-DEDA-42B8-9F9E-3B8A35044934) (Shutdown)
iPhone 6s Plus (109F57EA-6324-4BC9-9A02-ED088B76CDD3) (Shutdown)
iPhone 7 (AB44F116-3689-4980-9E74-59B0593CBD83) (Shutdown)
iPhone 7 Plus (1A90FA5C-CACC-402E-B39C-966442FBE222) (Shutdown)
iPhone SE (C5C9A0ED-09E7-4EA3-94C6-66F3ACBB4896) (Shutdown)
iPad Air (46AD7657-0C43-4889-8400-552EE8BB3F2E) (Shutdown)
iPad Air 2 (590A88CF-5D49-4A24-839D-15A4A9A67FC2) (Shutdown)
iPad Pro (9.7 inch) (8AF24C0E-7FCB-4096-A504-C399EEAC8CA8) (Shutdown)
iPad Pro (12.9 inch) (598A5895-DE76-4CD0-99C9-3D57CE137947) (Shutdown)
-- iOS 10.3 --
iPhone 5s 10.3.1 (09C758DE-3599-4370-AC28-23F3DB3C315B) (Shutdown)
-- iOS 12.0 --
-- iOS 12.1 --
iPhone 5s 12.1 (EB6D0DD8-B0CD-4B8B-B80A-E313296CAF99) (Shutdown)
iPhone X (C4FB86B6-17AC-45D7-99EB-70B91FA7E1F8) (Shutdown)
iPhone Xs Max (5460DF9C-E3D6-4EA8-ADC1-783683E34CC2) (Shutdown)
....
And more

but
`applesimutils --list` shows nothing:
```
[

]

```

**Steps to Reproduce**
run `applesimutils --list`

**Device, macOS and Xcode Versions**
macOS: 10.14.4, Xcode: 10.1 (10.2 also installed) Some time ago i upgrade Xcode from 10.1 to 10.2 (after that reinstall 10.1)

**Comment by Desintegrator** [comment]
applesimutils reinstalling (this upgrade applesimutils version from 0.6.2 to 0.6.8) solved this isuue

**Comment by LeoNatan** [comment]
Always use latest version before opening issues.

**Comment by billburgess** [comment]
I'm seeing this issue on version 0.6.6.

**Comment by billburgess** [comment]
Should I open a new issue for this or do you want to reopen it @LeoNatan?

**Comment by LeoNatan** [comment]
Please open a new issue and provide the necessary information, such as Xcode command line utils version, etc.
