### ISSUE TITLE
FaceID needs permissions.

### ISSUE THREAD

**Issue by abunsen** [wix/AppleSimulatorUtils#58]
**Description**
AppleSimUtils Touch/FaceID support is missing the ability to toggle the OS level permissions, in the same way that camera, location, etc need OS level permissions.

**Steps to Reproduce**
1. Add FaceID to your app (in our case, we're using `react-native-touch-id`) - code here:

```
LAContext *context = [[LAContext alloc] init];
    NSError *error;
    
    // Check to see if we have a passcode fallback
    NSNumber *passcodeFallback = [NSNumber numberWithBool:true];
    if (RCTNilIfNull([options objectForKey:@"passcodeFallback"]) != nil) {
        passcodeFallback = [RCTConvert NSNumber:options[@"passcodeFallback"]];
    }
    
    if ([context canEvaluatePolicy:LAPolicyDeviceOwnerAuthenticationWithBiometrics error:&error]) {
        
        // No error found, proceed
        callback(@[[NSNull null], [self getBiometryType:context]]);
    } else if ([passcodeFallback boolValue] && [context canEvaluatePolicy:LAPolicyDeviceOwnerAuthentication error:&error]) {
        
        // No error
        callback(@[[NSNull null], [self getBiometryType:context]]);
    }
    // Device does not support FaceID / TouchID / Pin OR there was an error!
    else {
        if (error) {
            NSString *errorReason = [self getErrorReason:error];
            NSLog(@"Authentication failed: %@", errorReason);
            
            callback(@[RCTMakeError(errorReason, nil, nil), [self getBiometryType:context]]);
            return;
        }
        
        callback(@[RCTMakeError(@"RCTTouchIDNotSupported", nil, nil)]);
        return;
    }
```
2. Attempt to use FaceID
3. You're met with a prompt like the following:
![Image from iOS](https://user-images.githubusercontent.com/93429/62497924-69925880-b7ab-11e9-975b-eac1ffe390fe.png)

**Expected Behavior**
It would be ideal with we could set the permissions at the command line level, in the same way we set permissions for camera, location, etc.

**Comment by brandons** [comment]
+1 I'm not sure how anyone is able to use the Face ID utils without this.

**Comment by brandons** [comment]
@abunsen PR up to add ability to toggle FaceID permission setting. Can you test and let me know if this works for you? https://github.com/wix/AppleSimulatorUtils/pull/59

**Comment by LeoNatan** [comment]
0.7.1 out with fix by @brandons 
Thanks!
