### ISSUE TITLE
Can not find simulators after upgrade Xcode from 8.3.3

### ISSUE THREAD

**Issue by irrigator** [wix/AppleSimulatorUtils#6]
#### Description

Works find before but it can not find simulators after upgrade Xcode from 8.3.3, either by name or by simulator id.

#### Steps to Reproduce

run  ```applesimutils --simulator "iPhone 6, OS = 10.3" --bundle "com.ancientmd.dingtcm.test" --setPermissions "notifications=YES, location=always, camera=YES"```

#### Device, macOS and Xcode Versions
newest macOS and Xcode

**Comment by LeoNatan** [comment]
Please paste the result of running the following command:
```xcrun simctl list devices```

Thanks

**Comment by irrigator** [comment]
== Devices ==
-- iOS 10.3 --
    iPhone 5 (CC2780BB-76A2-4EC7-A2FE-A1098F987B25) (Shutdown)
    iPhone 5s (E27DAC62-D837-43BF-BCBC-0C1B88E1F28B) (Shutdown)
    iPhone 6 (09090B3A-C584-428F-AC2C-91494BBC8667) (Booted)
    iPhone 6 Plus (00C9156C-0418-4980-8FD8-966EADE83A50) (Shutdown)
    iPhone 6s (63BAABF4-6BB2-4C93-A990-EFDA9A8E7F4F) (Shutdown)
    iPhone 6s Plus (770AA100-789B-4AC5-8DA9-A4F09DB6BEDF) (Shutdown)
    iPhone 7 (C5CD23AB-4123-4C2D-BEAD-FC74F884AA9F) (Shutdown)
    iPhone 7 Plus (37846B62-6016-408C-A087-545E97257BB9) (Shutdown)
    iPhone SE (ADB3A814-6D12-4FFD-BA53-20D81FC89A13) (Booted)
    iPad Air (A37AE789-B56C-4650-BE3D-931F038F72E1) (Shutdown)
    iPad Air 2 (E38B7FA1-DD07-4F07-8595-4C2E8D787D96) (Shutdown)
    iPad Pro (9.7 inch) (D6C46C76-4801-4D8A-8E65-914910F02AC3) (Shutdown)
    iPad Pro (12.9 inch) (196C2527-C166-426C-A6E8-C1E4CA8F3D78) (Shutdown)
-- tvOS 10.2 --
    Apple TV 1080p (7C72AD07-B717-4418-A05F-9C3B3690F054) (Shutdown)
-- watchOS 3.2 --
    Apple Watch - 38mm (7DCD9394-44A2-489D-8DD6-74673243FA61) (Shutdown)
    Apple Watch - 42mm (33045090-E5C0-431E-B8EB-C9CF44A22ADD) (Shutdown)
    Apple Watch Series 2 - 38mm (4454EC08-68E0-4715-9A2B-A72D17920D7F) (Shutdown)
    Apple Watch Series 2 - 42mm (0A460308-5DA1-42BF-A234-84B0AF492B27) (Shutdown)

**Comment by LeoNatan** [comment]
These devices should be discoverable by `applesimutils`.

**Comment by irrigator** [comment]
The command ```applesimutils --simulator "iPhone 6, OS = 10.3" --bundle "com.ancientmd.dingtcm.test" --setPermissions "notifications=YES, location=always, camera=YES"``` failed with error message "Error: No simulator found matching “iPhone 6, OS = 10.3”". It used to work correctly before I upgraded Xcode to 8.3.3.

**Comment by irrigator** [comment]
Update
I tried to use identifier instead of simulator name, and it worked!

**Comment by LeoNatan** [comment]
I see. So something must have broken the search algorithm. I’ll look.

**Comment by irrigator** [comment]
Thanks a lot. Could you please point me to the related code? Although I don't know Objective-C, I will try to help by investigating this issue.

**Comment by LeoNatan** [comment]
The search is performed in the main function here:
https://github.com/wix/AppleSimulatorUtils/blob/master/applesimutils/applesimutils/main.m

**Comment by LeoNatan** [comment]
I think I know what the issue is. The OS has been updated to 10.3.1 in Xcode 8.3.3, and thus there is no 10.3 device. Update your command to be 10.3.1. Thanks.

**Comment by Desintegrator** [comment]
Have same issue xcode 10.1

`xcrun simctl list devices` shows:

-- iOS 10.2 --
    iPhone 5s 10.2 (A86D0F25-0A31-4E26-B843-662BB715A758) (Shutdown) 
    iPhone 6 (B0F904AB-F0E0-4680-B611-7CD405592AD5) (Shutdown) 
    iPhone 6 Plus (7967BA29-3033-4376-96F5-2AFCD7892633) (Shutdown) 
    iPhone 6s (0A64B869-DEDA-42B8-9F9E-3B8A35044934) (Shutdown) 
    iPhone 6s Plus (109F57EA-6324-4BC9-9A02-ED088B76CDD3) (Shutdown) 
    iPhone 7 (AB44F116-3689-4980-9E74-59B0593CBD83) (Shutdown) 
    iPhone 7 Plus (1A90FA5C-CACC-402E-B39C-966442FBE222) (Shutdown) 
    iPhone SE (C5C9A0ED-09E7-4EA3-94C6-66F3ACBB4896) (Shutdown) 
    iPad Air (46AD7657-0C43-4889-8400-552EE8BB3F2E) (Shutdown) 
    iPad Air 2 (590A88CF-5D49-4A24-839D-15A4A9A67FC2) (Shutdown) 
    iPad Pro (9.7 inch) (8AF24C0E-7FCB-4096-A504-C399EEAC8CA8) (Shutdown) 
    iPad Pro (12.9 inch) (598A5895-DE76-4CD0-99C9-3D57CE137947) (Shutdown) 
-- iOS 10.3 --
    iPhone 5s 10.3.1 (09C758DE-3599-4370-AC28-23F3DB3C315B) (Shutdown) 
-- iOS 12.0 --
-- iOS 12.1 --
    iPhone 5s 12.1 (EB6D0DD8-B0CD-4B8B-B80A-E313296CAF99) (Shutdown) 
    iPhone X (C4FB86B6-17AC-45D7-99EB-70B91FA7E1F8) (Shutdown) 
    iPhone Xs Max (5460DF9C-E3D6-4EA8-ADC1-783683E34CC2) (Shutdown) 
....
And more

but
`applesimutils --list` show nothing
[

]

**Comment by LeoNatan** [comment]
@Desintegrator Please open a new issue.
