### ISSUE TITLE
Support for Bluetooth Permission

### ISSUE THREAD

**Issue by billburgess** [wix/AppleSimulatorUtils#61]
Starting in iOS 13, just touching the CBCentralManager will trigger a permission dialog for Bluetooth. This tool has been vital to bypassing system dialogs in unit testing. It makes sense for this library to support this if possible.

**Comment by LeoNatan** [comment]
I'll take a look at this when possible. PRs are welcome.

**Comment by LeoNatan** [comment]
Hi Bill,

Looping into this. I can't seem to trigger bluetooth permission alerts on the simulator... Any code examples I can use to investigate?

**Comment by billburgess** [comment]
@LeoNatan Bluetooth does not work in the Simulator no matter what I try. I have not been able to trigger this warning in the sim as of yet. It is possible that someone would bump into it if running tests on an actual device.

**Comment by LeoNatan** [comment]
Yes, but Apple**Simulator**Utils is about Apple simulators. 😂

**Comment by LeoNatan** [comment]
I saw the string related to this in the framework, but it seems impossible to trigger on simulators. So closing the issue for now. If you trigger it, let me know and I'll reopen. Thanks.

**Comment by billburgess** [comment]
Yeah, saw the new permission when I made this, but hasn't ever been an issue in practice.
