### ISSUE TITLE
More information on this (question)

### ISSUE THREAD

**Issue by patchthecode** [wix/AppleSimulatorUtils#64]
Hi, I am unclear on what this project does based on the readme page.
I saw it mentioned permissions 
```
Available Permissions:
    calendar=YES|NO|unset
    camera=YES|NO|unset
    contacts=YES|NO|unset
    faceid=YES|NO|unset
    health=YES|NO|unset (iOS 12.0 and above)
    homekit=YES|NO|unset
    location=always|inuse|never|unset
    medialibrary=YES|NO|unset
    microphone=YES|NO|unset
    motion=YES|NO|unset
    notifications=YES|NO|unset
    photos=YES|NO|unset
    reminders=YES|NO|unset
    siri=YES|NO|unset
    speech=YES|NO|unset
```

Does this mean it has the ability to disable permissions for an app?
Maybe a more user friendly readme will help some like me. thanks.

**Comment by LeoNatan** [comment]
This is a tool that is usually used in automation tools, such as Detox and Appium. As such, quoting the `--help` output is enough.

> --setPermissions, -sp         Sets the specified permissions and restarts SpringBoard for the changes to take effect

You use this command to set specified permissions (enabled, disabled or unset) for an app. This is useful when running tests and you do not want the system alerts to appear.

**Comment by patchthecode** [comment]
thank you

**Comment by LeoNatan** [comment]
Is there something specific you are looking for?

**Comment by patchthecode** [comment]
Yes, I am looking to see how you prevented iOS permission messages from appearing, as I need it in a project I am working on. I could not tell if this project had this. But you have made it clear to me that it does. So thank you.

**Comment by LeoNatan** [comment]
The code you see here will only work on iOS Simulator, and cannot be run from the process you are running.

**Comment by patchthecode** [comment]
I am sorry, but can you explain a bit more?

> The code you see here will only work on iOS Simulator

I understand this.

> and cannot be run from the process you are running.

But you lost me here

**Comment by LeoNatan** [comment]
The code in this repo modifies system database files to add the appropriate permission for the specified bundle. This might be possible on the simulator the app process, but the way runtime permissions work on iOS, you will need to terminate the app process, sometimes a daemon has to be stopped before modifying permissions, and in some cases, you need to restart the SpringBoard process in order for the changes to accept. You cannot do these things from the app process.

**Comment by patchthecode** [comment]
Thanks for the explanation.
I understand now.
I will not worry, I have a way to make this all work together.
Thanks again.
