### ISSUE TITLE
Notification Permission not setting for Xcode 11.3

### ISSUE THREAD

**Issue by billburgess** [wix/AppleSimulatorUtils#67]
I know there is an open issue for this tied to 11.1. This issue is back with a vengeance with the latest version of Xcode 11.3.1. It is happening on virtually all of my test runs, local and CI. The other issue is not allowing comments, so I wanted to ping you with a new issue to see if we can look into this. Thanks in advance.

**Comment by billburgess** [comment]
The notification permission is set correctly using Xcode 11.3.1 when using older runtimes. I can run against 10, 11, and 12 and the notifications are set correctly. It's only when running against iOS 13.3.

**Comment by LeoNatan** [comment]
Thanks for checking. Most likely things moved again, or something changed in the way notifications are saved.

**Comment by LeoNatan** [comment]
Unfortunately, unable to reproduce. Running applesimutils for an iOS 13.3 simulator, notification permissions are set correctly for `YES` and `NO`.

**Comment by billburgess** [comment]
Could this be an issue with macOS or bash? Or a verbose option to see what happens during the script run?

**Comment by billburgess** [comment]
```
xcrun simctl shutdown all
xcrun simctl delete iOS11TestDevice || echo Failed to delete iOS 11 device
xcrun simctl create iOS13TestDevice "iPhone 11" com.apple.CoreSimulator.SimRuntime.iOS-13-3
xcrun instruments -w "iOS13TestDevice" || sleep 30
applesimutils --byName "iOS13TestDevice" --bundle "simpleinout" --setPermissions "notifications=YES, location=always, contacts=YES" || sleep 30
```

This is the script I use before launching my test suite. Do you see any issues with this kind of setup?

**Comment by LeoNatan** [comment]
I don't see anything wrong. I'm not sure what the instruments line does, but I assume it boots the device? BTW, it shouldn't be necessary to boot the device before setting permissions.

**Comment by LeoNatan** [comment]
Could I ask you to clone this repo and run the demo app in the repo? It's just a test app which tests for different permissions. Try setting only notification permission to YES and clicking the button in the test app.

**Comment by billburgess** [comment]
The instruments line does boot the app. I can remove it if it isn't needed for any of the sims. Will speed my suite up quite a bit not having to sleep 30 for each run. I'll report back on the demo app.

**Comment by LeoNatan** [comment]
It should work without booting, as everything is performed on static files on the disk.

Thanks

**Comment by billburgess** [comment]
Ok, the same app does not work for me. Here is what I did.

1. Created a brand new iPhone 11 test device on iOS 13.3 (used device manager in Xcode)
2. Navigated in terminal to the sample folder of the repo.
3. Ran this command `applesimutils --byName "AppleUtilsTest" --bundle "PermissionsTest" --setPermissions "notifications=YES"`
4. The command in terminal took about 15 seconds before it completed. Which feels very long.
5. Ran the sample app and clicked on the notifications button which triggered the system prompt.

Something is goofy. Let me know what you'd like to see or have me try.

**Comment by LeoNatan** [comment]
I think I see the problem. That is not the bundle. The bundle is the bundle identifier of the app.

**Comment by LeoNatan** [comment]
The longer run time is because it's a new simulator, the files don't exist. So applesimutils boots the device silently so the files are created. That's still shorter than 30 seconds. The next run will take a lot less.

**Comment by billburgess** [comment]
In my app at least, the bundle is very short and is actually `simpleinout`.

I created a new device, retested with the right bundle name and it worked. So... what am I doing wrong with my main runs and test suite that is different than this?

**Comment by LeoNatan** [comment]
OK, if it works, lets try to weed out the cause... Try running the same script you are running in production, but for the test app. Then see if it works.

**Comment by billburgess** [comment]
Ok, test 3. I created the device via command line like my suite does. Set permissions with my script (subbing the sample app bundle and device). I got a weird message that I didn't before.
 `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/LaunchDaemons/com.apple.locationd.plist: Operation now in progress`

It finished and I ran the sample app and it worked.

**Comment by billburgess** [comment]
I removed the 30 second wait from my build script and ran my tests locally again, and it worked this time. I'll keep running it to see if it fails again, or I can add the wait back and see if that causes it to fail.

**Comment by LeoNatan** [comment]
I find that an odd reason to be the cause. A booted simulator shouldn't be causing the issue.

**Comment by billburgess** [comment]
I wouldn't think so either. I tried another test with the sample app and it didn't affect it at all. So I'm not sure. There does seem to be some randomness to it, but I still can't quite figure it out.

**Comment by LeoNatan** [comment]
So your own app still fails?
Also, when running for the test app, are you setting all the permissions together, as you do for your own app? Maybe that somehow influences it...

**Comment by billburgess** [comment]
I removed the sleep from my script as well as the call to pre-start the simulator and it worked this time. The sample app has worked every time no matter what I do to it. Sleep, pre-start, the sample always works.

**Comment by LeoNatan** [comment]
I've released a new version with a proposed fix/workaround. Could you pls test and see that things work better now for you? @billburgess

**Comment by billburgess** [comment]
I’ll give it a go when I get to the office later this morning. Thanks for looking into this.

**Comment by LeoNatan** [comment]
Great, thanks!

**Comment by billburgess** [comment]
I reverted to the changes in my scripts with the simulator pre starts which is where I usually had issues. So far, no issues with the new changes. I'll keep an eye on it and let you know if I run into any issues with it.

**Comment by LeoNatan** [comment]
Great. We hope for the best.

**Comment by billburgess** [comment]
I'll ping you if it happens again. Thanks for the help.
