### ISSUE TITLE
The end of AppleSimUtils?

### ISSUE THREAD

**Issue by LeoNatan** [wix/AppleSimulatorUtils#68]
From Xcode 11.4 beta release notes:

![simctl](https://user-images.githubusercontent.com/2270433/73889672-e7c5d980-4878-11ea-872e-7149ac507bb6.png)

We will need to reevaluate our need for this tool following this development. We may want to just passthrough user commands to the built-in system in case of Xcode 11.4, while keeping the legacy systems in place for backwards compatibility.

**Comment by billburgess** [comment]
Any reason to think this won’t work with older runtimes or the need to have branched logic? This is great news, hopefully it will work with any runtime.

**Comment by LeoNatan** [comment]
The runtimes will work. I meant backwards compatibility with older Xcode versions. Xcode 11.4 requires Catalina, so I'm pretty sure many will not hurry to update. But in that case, AppleSimUtils can be deprecated and left as-is. We use it for other stuff as well (filtering of simulators and other stuff), so we'll need to think what to do with the tool.

**Comment by billburgess** [comment]
Sounds good. Not sure what the future holds for this tool, but I’m forever grateful for it. Thanks for all the hard work you’ve put into it.

**Comment by billburgess** [comment]
I downloaded the 11.4 beta to test things out, and it doesn't currently include support for notifications. :/ Using the command:

`scrum simctl privacy help` will output everything available. Notifications isn't listed at the moment. I'll likely file a radar for this, but if this permission is omitted from release, it won't be viable at all for CI testing.

Here is the full output from the help command:

```
Grant, revoke, or reset privacy and permissions
Usage: simctl privacy <device> <action> <service> [<bundle identifier>]

	action
	     The action to take:
	         grant - Grant access without prompting. Requires bundle identifier.
	         revoke - Revoke access, denying all use of the service. Requires bundle identifier.
	         reset - Reset access, prompting on next use. Bundle identifier optional.
	     Some permission changes will terminate the application if running.
	service
	     The service:
	         all - Apply the action to all services.
	         calendar - Allow access to calendar.
	         contacts-limited - Allow access to basic contact info.
	         contacts - Allow access to full contact details.
	         location - Allow access to location services when app is in use.
	         location-always - Allow access to location services at all times.
	         photos-add - Allow adding photos to the photo library.
	         photos - Allow full access to the photo library.
	         media-library - Allow access to the media library.
	         microphone - Allow access to audio input.
	         motion - Allow access to motion and fitness data.
	         reminders - Allow access to reminders.
	         siri - Allow use of the app with Siri.
	bundle identifier
	     The bundle identifier of the target application.

Examples:
	reset all permissions: privacy <device> reset all
	grant test host photo permissions: privacy <device> grant photos com.example.app.test-host

Warning:
Normally applications must have valid Info.plist usage description keys and follow the API guidelines to request access to services. Using this command to bypass those requirements can mask bugs.
```

**Comment by LeoNatan** [comment]
AppleSimUtils lives on! 🙃

Looks like these are the TCC permissions only (notifications isn't).

**Comment by billburgess** [comment]
What is a TCC permission?

**Comment by billburgess** [comment]
I've added a radar to try and get them to add this before it goes live. If anyone following this would like to dupe it, it would be appreciated. FB7566372.

**Comment by LeoNatan** [comment]
TCC stands for "Transparency, Consent, Control". It's one of the mechanisms Apple has for limiting access to data. Most runtime permissions are handled by this is system. There is a database (TCC.db) where each permission sits when granted, and a daemon (tccd) which is responsible for management of this system.

**Comment by LeoNatan** [comment]
More permissions are missing, such as Bluetooth and health.

**Comment by billburgess** [comment]
Ah, but notifications lives outside this paradigm? Odd that they are all presented and handled very similar, but notifications lives outside this.

http://www.openradar.appspot.com/radar?id=5029865547890688

I'll do my best to see if they can improve this before launch, but if it ends up being left out, then the need for this tool will remain. I'm not sure I'd even use the native stuff myself in favor of just one tool or command to handle everything. Maybe this tool calls the native stuff underneath.

**Comment by LeoNatan** [comment]
Notifications are handled fully in Springboard. There is a plist file which includes all the permissions.

**Comment by billburgess** [comment]
Good point. Forgot to add those to my radar. But could dupe it with mine and request those.

**Comment by LeoNatan** [comment]
I'm opening a feedback now with a more general title "missing services".

**Comment by billburgess** [comment]
Sounds good

**Comment by LeoNatan** [comment]
FB7566382

**Comment by billburgess** [comment]
Have you cloned this to open radar yet? I'd like to copy your text and title.

**Comment by LeoNatan** [comment]
Sure: https://openradar.appspot.com/radar?id=5034242388000768

**Comment by billburgess** [comment]
Duped
