### ISSUE TITLE
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.

### ISSUE THREAD

**Issue by zeritte** [wix/AppleSimulatorUtils#69]
**Description**
I am trying to build a react native app on circleci by using reactnativecommunity/react native orb. Using the latest version. However when it comes to `applesimutils --list` part it fails with the following error:
`Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.`

`xcrun simctl list devices` shows devices.

**Steps to Reproduce**
Node v19.0, The latest AppleSimulatorUtils & reactnativecommunity/react native orb. Go to circle ci and apple rn/ios_build_and_test

**Expected Behavior**
It should list devices & filter them by type if `byType...` is added.

```
detox[24759] INFO:  [test.js] configuration="ios.sim.release" loglevel="warn" headless=true reportSpecs=true useCustomLogger=true DETOX_START_TIMESTAMP=1584759599275 node_modules/.bin/jest --config e2e/config.json '--testNamePattern=^((?!:android:).)*$' --maxWorkers 1 "e2e"
detox[25328] ERROR: [exec.js/EXEC_FAIL, #0] "applesimutils --list --byType "iPhone X"" failed with code = 255, stdout and stderr:

detox[25328] ERROR: [exec.js/EXEC_FAIL, #0] 
detox[25328] ERROR: [exec.js/EXEC_FAIL, #0] v10.19.0 is already installed.
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.

Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.


detox[25328] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 { ChildProcessError: Command failed: applesimutils --list --byType "iPhone X"
v10.19.0 is already installed.
Error: The data couldn’t be read because it isn’t in the correct format.. See “applesimutils --help” for usage.

Error: Unable to obtain a list of simulators. See “applesimutils --help” for usage.
```

**Comment by springcoil** [comment]
+ 1 this one.

**Comment by zeritte** [comment]
`xcrun simctl list --json` also works

**Comment by LeoNatan** [comment]
Hi guys,

Can you please state what Xcode and what version of AppleSimUtils you are using? 

Thanks!

**Comment by zeritte** [comment]
> Hi guys,
> 
> Can you please state what Xcode and what version of AppleSimUtils you are using?
> 
> Thanks!

AppleSimUtils version is 0.7.7
Xcode 10.1
Build version 10B61
this is running on circle ci fyi.

**Comment by LeoNatan** [comment]
Unfortunately, 10.1 is very old version of Xcode. If you can, please use a newer version of Xcode, such as 10.3, or find an older version of AppleSimUtils that works with your version.

**Comment by zeritte** [comment]
hey!
Thank you for quick response. I will try to make the versions match.
Have a good day

**Comment by LeoNatan** [comment]
If you find a version of AppleSimUtils that works, I can compare to see what could have caused the issue. Let me know.
