### ISSUE TITLE
Support for iOS 14 track permission

### ISSUE THREAD

**Issue by HackingGate** [wix/AppleSimulatorUtils#73]
Starting in iOS 14. AppTrackingTransparency framework is required to get device’s advertising identifier.
Details here https://developer.apple.com/app-store/user-privacy-and-data-use/

**Comment by LeoNatan** [comment]
Hello,

Can you please provide a small, native (not RN) example project where this API is invoked?

Thnaks

**Comment by HackingGate** [comment]
@LeoNatan 

I added example in #74

I also took a look into [Singular-SKAdNetwork-App](https://github.com/singular-labs/Singular-SKAdNetwork-App). Both IDFA(legacy) and SKAdNetwork use the same logic to request permission.
Changing title.

**Comment by LeoNatan** [comment]
Cool, thanks!
I’ll try looking into it soon.
