### ISSUE TITLE
Unable to bypass permission alerts in ios while performing integration testing. 

### ISSUE THREAD

**Issue by TharaniP** [wix/AppleSimulatorUtils#75]
Hi, I am trying to bypass the permission alerts in ios while performing integration testing using flutter driver. To perform that, i have installed "applesimutils" in my system and written the below line inside app_test.dart file:     

   Process.run('applesimutils', ["--byId", 'deviceId', "--bundle", 'bundleId', "--setPermissions", "notifications=YES"]);
 
While executing the integration test, app is getting closed immediately, after the execution of this line.  

I have referred this link : https://github.com/flutter/flutter/issues/12561#issuecomment-507484574
 
**Expected Behavior**
"Process.run('applesimutils', ["--byId", 'deviceId', "--bundle", 'bundleId', "--setPermissions", "notifications=YES"]);" should bypass permission alerts while performing integration testing in flutter. 

**Environment**
 - macOS version: 10.14.6
 - Xcode version: 11.3.1

**Comment by LeoNatan** [comment]
Do you get any error? The tool is tested on many CI machines and environments, especially with Xcode 11.3.1. You might be calling it incorrectly.

**Comment by TharaniP** [comment]
I am getting this error: VMServiceFlutterDriver: Instance of '_WebSocketImpl' is closed with an unexpected code 1005.

**Comment by LeoNatan** [comment]
I’m sorry, this is telling me nothing. This tool is not a flutter tool. Run this in your command line, with all the arguments, and see what error you are getting there.

**Comment by billburgess** [comment]
It looks like it is being called from inside the test, which would cause the sim to restart and make the test fail for odd reasons.

**Comment by LeoNatan** [comment]
@billburgess Do you mean the springboard restart? I think that is synchronous inside applesimutils

**Comment by billburgess** [comment]
Right, but if called on the sim while it was running tests would cause issues.

**Comment by TharaniP** [comment]
I am calling before this line:- driver = await FlutterDriver.connect();
so at that time test cases will not be running.

**Comment by LeoNatan** [comment]
Please run the command in Terminal and post the output here. Thanks

**Comment by TharaniP** [comment]
I want to run this command:- applesimutils --byId deviceId --bundle com.xxxx.xxxxx --setPermissions "notifications=YES, location=inuse, camera=YES, photos=YES, microphone=YES”. 

To run the above command do i need to specify any path?

**Comment by LeoNatan** [comment]
No, no path. Just make sure to pass a proper simulator id (not “deviceId”).

**Comment by TharaniP** [comment]
After running this command:  applesimutils --byId simulatorId --bundle com.XXXX.XXXX --setPermissions "notifications=YES,location=inuse,camera=YES,photos=YES,microphone=YES” in terminal, its expecting the user to enter something. But i did not get any error.

**Comment by LeoNatan** [comment]
?

I’m sorry, but you are running it wrong.
