### ISSUE TITLE
Not working on M1 based Macs

### ISSUE THREAD

**Issue by billburgess** [wix/AppleSimulatorUtils#77]
When running the command on a newly set up Mac (M1 Based MacBook Pros) an error is thrown.

```console
applesimutils --byName "iPod touch (7th generation)" --bundle "myappdomain" --setPermissions "notifications=YES, location=always, contacts=YES"
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Invalid device state
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Invalid device state
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Invalid device state
```

**Steps to Reproduce**
applesimutils --byName "iPod touch (7th generation)" --bundle "myappdomain" --setPermissions "notifications=YES, location=always, contacts=YES"

**Expected Behavior**
Should set permissions and reset running sim.

**Environment**
macOS 11 (Big Sur)
Xcode 12.3

**Additional Context**
Feels like an M1 issue, but not sure. This came about when trying to streamline our onboarding process for new users. Installation via brew is fine, but it fails to run for them, same error each time.

**Comment by LeoNatan** [comment]
Hi Bill,

I think this is an Apple bug, but let's debug it. I just released a new version with debug logging. Please install that on your m1 machine, and execute the following command:

```sh
log stream --level debug --style compact --predicate "subsystem=='com.wix.applesimutils'"
```

Thanks

**Comment by billburgess** [comment]
Here is the output from the debugged run. I think I may have a line on the problem though. We did not see this error when it ran against phone devices. The error only showed up when the command ran against the iPod Touch (7th generation) device. Is the permissions file in a different location or does that device have unsupported permissions? My users shouldn't have chosen that device, but curious why it would fail. Let me know if you need more output.

```console
2020-12-21 12:31:05.763 Db applesimutils[99414:1e9c70] [com.wix.applesimutils:CLI] Running “/usr/bin/xcrun” with arguments: “simctl get_app_container 1615D724-319E-4A97-9276-61CE8CDD4E9B simpleinout app”
2020-12-21 12:31:05.891 Db applesimutils[99414:1e9c70] [com.wix.applesimutils:CLI] Running “/usr/bin/which” with argument: “xcode-select”
2020-12-21 12:31:05.905 Db applesimutils[99414:1e9c70] [com.wix.applesimutils:CLI] Running “/usr/bin/xcode-select” with argument: “-p”
2020-12-21 12:31:06.396 Db applesimutils[99414:1e9c70] [com.wix.applesimutils:CLI] Setting service “kTCCServiceAddressBook” permission
```

**Comment by LeoNatan** [comment]
Thanks

Can you also please correlate the `Invalid device state` error messages with the corresponding debug log?

**Comment by billburgess** [comment]
These error messages only showed up when running the tool against the iPod Touch. I did not see this error for any other device.

**Comment by LeoNatan** [comment]
Interesting, I will try to reproduce this on iPod Touch locally. So as a workaround, you guys can use an iPhone simulator, and everything works as expected?

**Comment by billburgess** [comment]
Correct. Not as big an issue as I initially thought. Higher ups have newer machines and were having issues. I'm passing debug info along as an intermediary. Anecdotally, the tests did run and the permissions did appear to set in spite of the error message.

**Comment by LeoNatan** [comment]
I managed to reproduce the issue on an "iPod touch (7th generation)". Investigating

**Comment by LeoNatan** [comment]
Fixed in 0.9.2

**Comment by billburgess** [comment]
Thanks for looking into this!

**Comment by rafaelDevloft** [comment]
For any future readers: i had the same issue. I solved by making sure the whole environment (node etc) was using the arm architecture instead of rosetta.
